import fs from "node:fs";
import path from "node:path";
import { projectDir } from "./paths.js";
import { validateEntitySpec, modelAccessor, routeSegment, type EntitySpec } from "./types.js";

const SCHEMA_MARKER = "// @hermes:crud-models-below";

function prismaModelBlock(entity: EntitySpec): string {
  const fieldLines = entity.fields.map((field) => `  ${field}   String`).join("\n");
  return `
model ${entity.name} {
  id        String   @id @default(cuid())
${fieldLines}
  createdAt DateTime @default(now())
}
`;
}

function appendPrismaModel(projectName: string, entity: EntitySpec): void {
  const schemaPath = path.join(projectDir(projectName), "prisma", "schema.prisma");
  const schema = fs.readFileSync(schemaPath, "utf8");
  if (!schema.includes(SCHEMA_MARKER)) {
    throw new Error(`schema.prisma is missing the "${SCHEMA_MARKER}" marker — cannot append the entity model`);
  }
  if (new RegExp(`model ${entity.name} \\{`).test(schema)) {
    throw new Error(`Entity "${entity.name}" already exists in schema.prisma`);
  }
  const updated = schema.replace(SCHEMA_MARKER, `${SCHEMA_MARKER}${prismaModelBlock(entity)}`);
  fs.writeFileSync(schemaPath, updated, "utf8");
}

function collectionRouteContent(entity: EntitySpec): string {
  const accessor = modelAccessor(entity.name);
  const fieldsArray = JSON.stringify(entity.fields);
  return `import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getCurrentUser } from "@/lib/currentUser";

// Generated by @hermes/saas-factory. The Prisma accessor is looked up
// dynamically by model name so this route works for any generated entity;
// that trades static typing on the accessor for a fully generic generator.
const model = (prisma as unknown as Record<string, any>)["${accessor}"];
const FIELDS = ${fieldsArray} as const;

export async function GET() {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const items = await model.findMany({ orderBy: { createdAt: "desc" } });
  return NextResponse.json(items);
}

export async function POST(request: NextRequest) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await request.json().catch(() => null);
  if (!body || typeof body !== "object") {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const data: Record<string, string> = {};
  for (const field of FIELDS) {
    const value = (body as Record<string, unknown>)[field];
    if (typeof value !== "string" || value.length === 0) {
      return NextResponse.json({ error: \`Field "\${field}" is required and must be a non-empty string\` }, { status: 400 });
    }
    data[field] = value;
  }

  const item = await model.create({ data });
  return NextResponse.json(item, { status: 201 });
}
`;
}

function itemRouteContent(entity: EntitySpec): string {
  const accessor = modelAccessor(entity.name);
  const fieldsArray = JSON.stringify(entity.fields);
  return `import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { getCurrentUser } from "@/lib/currentUser";

const model = (prisma as unknown as Record<string, any>)["${accessor}"];
const FIELDS = ${fieldsArray} as const;

export async function GET(_request: NextRequest, { params }: { params: { id: string } }) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const item = await model.findUnique({ where: { id: params.id } });
  if (!item) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json(item);
}

export async function PATCH(request: NextRequest, { params }: { params: { id: string } }) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await request.json().catch(() => null);
  if (!body || typeof body !== "object") {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const data: Record<string, string> = {};
  for (const field of FIELDS) {
    const value = (body as Record<string, unknown>)[field];
    if (value !== undefined) {
      if (typeof value !== "string" || value.length === 0) {
        return NextResponse.json({ error: \`Field "\${field}" must be a non-empty string\` }, { status: 400 });
      }
      data[field] = value;
    }
  }

  const item = await model.update({ where: { id: params.id }, data }).catch(() => null);
  if (!item) return NextResponse.json({ error: "Not found" }, { status: 404 });
  return NextResponse.json(item);
}

export async function DELETE(_request: NextRequest, { params }: { params: { id: string } }) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  await model.delete({ where: { id: params.id } }).catch(() => null);
  return new NextResponse(null, { status: 204 });
}
`;
}

function dashboardListPageContent(entity: EntitySpec): string {
  const accessor = modelAccessor(entity.name);
  const headerCells = entity.fields.map((f) => `            <th className="py-2 pr-4">${f}</th>`).join("\n");
  const bodyCells = entity.fields
    .map((f) => `              <td className="py-2 pr-4">{item.${f}}</td>`)
    .join("\n");

  return `import { prisma } from "@/lib/db";

export default async function ${entity.name}sPage() {
  const items = await (prisma as unknown as Record<string, any>)["${accessor}"].findMany({
    orderBy: { createdAt: "desc" },
  });

  return (
    <section>
      <h1 className="text-2xl font-bold text-slate-900">${entity.name}s</h1>
      <table className="mt-6 w-full border-collapse text-sm">
        <thead>
          <tr className="border-b border-slate-200 text-left text-slate-500">
${headerCells}
          </tr>
        </thead>
        <tbody>
          {items.map((item: any) => (
            <tr key={item.id} className="border-b border-slate-100">
${bodyCells}
            </tr>
          ))}
        </tbody>
      </table>
    </section>
  );
}
`;
}

export function generateEntityCrud(projectName: string, entity: EntitySpec): void {
  validateEntitySpec(entity);
  appendPrismaModel(projectName, entity);

  const segment = routeSegment(entity.name);
  const root = projectDir(projectName);

  const apiDir = path.join(root, "app", "api", segment);
  fs.mkdirSync(apiDir, { recursive: true });
  fs.writeFileSync(path.join(apiDir, "route.ts"), collectionRouteContent(entity), "utf8");

  const apiItemDir = path.join(apiDir, "[id]");
  fs.mkdirSync(apiItemDir, { recursive: true });
  fs.writeFileSync(path.join(apiItemDir, "route.ts"), itemRouteContent(entity), "utf8");

  const dashboardDir = path.join(root, "app", "dashboard", segment);
  fs.mkdirSync(dashboardDir, { recursive: true });
  fs.writeFileSync(path.join(dashboardDir, "page.tsx"), dashboardListPageContent(entity), "utf8");
}
