import fs from "node:fs";
import path from "node:path";
import { SAAS_TEMPLATE_DIR, projectDir } from "./paths.js";
import type { SaasSpec } from "./types.js";

function siteConfigContent(spec: SaasSpec): string {
  return `// Generated by @hermes/saas-factory. Do not edit by hand.
export interface SiteConfig {
  name: string;
  description: string;
}

export const siteConfig: SiteConfig = ${JSON.stringify(
    { name: spec.siteName, description: spec.siteDescription },
    null,
    2,
  )};
`;
}

export function scaffoldSaas(spec: SaasSpec): void {
  if (!fs.existsSync(SAAS_TEMPLATE_DIR)) {
    throw new Error(`SaaS template not found at ${SAAS_TEMPLATE_DIR}`);
  }

  const target = projectDir(spec.projectName);
  fs.mkdirSync(target, { recursive: true });
  fs.cpSync(SAAS_TEMPLATE_DIR, target, { recursive: true });

  fs.writeFileSync(path.join(target, "lib", "site-config.ts"), siteConfigContent(spec), "utf8");
}
