// Generated by @hermes/website-factory. Describes this site's identity and
// navigation so components/layout stay generic across every generated site.
export interface NavLink {
  href: string;
  label: string;
}

export interface SiteConfig {
  name: string;
  description: string;
  nav: NavLink[];
}

export const siteConfig: SiteConfig = {
  name: "Hermes Site",
  description: "A website generated by the Hermes Digital Factory.",
  nav: [{ href: "/", label: "Home" }],
};
