// Generated by @hermes/saas-factory. Do not edit by hand.
export interface SiteConfig {
  name: string;
  description: string;
}

export const siteConfig: SiteConfig = {
  name: "Hermes SaaS",
  description: "A SaaS application generated by the Hermes Digital Factory.",
};
