import fs from "node:fs";
import path from "node:path";
import { ALL_PAGE_KINDS, pageDef, type PageKind, type WebsiteSpec } from "./types.js";
import { projectDir } from "./paths.js";

function metadataBlock(title: string, description: string): string {
  return `export const metadata: Metadata = {
  title: ${JSON.stringify(title)},
  description: ${JSON.stringify(description)},
};

`;
}

function homePageContent(spec: WebsiteSpec): string {
  const def = pageDef("home", spec.siteName);
  const hasContact = spec.pages.includes("contact");

  const heroBody = hasContact
    ? `    <Hero title=${JSON.stringify(spec.siteName)} subtitle=${JSON.stringify(spec.siteDescription)}>
      <Link
        href="/contact"
        className="inline-flex items-center justify-center rounded-md bg-slate-900 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-slate-700"
      >
        Get in touch
      </Link>
    </Hero>`
    : `    <Hero title=${JSON.stringify(spec.siteName)} subtitle=${JSON.stringify(spec.siteDescription)} />`;

  return `import type { Metadata } from "next";
import Link from "next/link";
import { Hero } from "@/components/Hero";

${metadataBlock(def.title, def.description)}export default function HomePage() {
  return (
${heroBody}
  );
}
`;
}

function aboutPageContent(spec: WebsiteSpec): string {
  const def = pageDef("about", spec.siteName);
  return `import type { Metadata } from "next";

${metadataBlock(def.title, def.description)}export default function AboutPage() {
  return (
    <section className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-bold text-slate-900">About ${spec.siteName}</h1>
      <p className="mt-4 text-base text-slate-600">
        ${spec.siteDescription}
      </p>
    </section>
  );
}
`;
}

function servicesPageContent(spec: WebsiteSpec): string {
  const def = pageDef("services", spec.siteName);
  return `import type { Metadata } from "next";
import { Card } from "@/components/Card";

${metadataBlock(def.title, def.description)}const SERVICES = [
  { title: "Consulting", description: "We help you plan the right approach." },
  { title: "Delivery", description: "We build and ship the work." },
  { title: "Support", description: "We keep things running afterward." },
];

export default function ServicesPage() {
  return (
    <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-bold text-slate-900">Services</h1>
      <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {SERVICES.map((service) => (
          <Card key={service.title} title={service.title}>
            {service.description}
          </Card>
        ))}
      </div>
    </section>
  );
}
`;
}

function projectsPageContent(spec: WebsiteSpec): string {
  const def = pageDef("projects", spec.siteName);
  return `import type { Metadata } from "next";
import { Card } from "@/components/Card";

${metadataBlock(def.title, def.description)}const PROJECTS = [
  { title: "Project One", description: "A recent project we delivered." },
  { title: "Project Two", description: "Another recent project we delivered." },
];

export default function ProjectsPage() {
  return (
    <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6">
      <h1 className="text-3xl font-bold text-slate-900">Projects</h1>
      <div className="mt-8 grid gap-6 sm:grid-cols-2">
        {PROJECTS.map((project) => (
          <Card key={project.title} title={project.title}>
            {project.description}
          </Card>
        ))}
      </div>
    </section>
  );
}
`;
}

function contactPageContent(spec: WebsiteSpec): string {
  const def = pageDef("contact", spec.siteName);
  return `import type { Metadata } from "next";
import { ContactForm } from "@/components/ContactForm";

${metadataBlock(def.title, def.description)}export default function ContactPage() {
  return (
    <section className="mx-auto max-w-3xl px-4 py-16 sm:px-6">
      <h1 className="text-center text-3xl font-bold text-slate-900">Contact ${spec.siteName}</h1>
      <div className="mt-8">
        <ContactForm />
      </div>
    </section>
  );
}
`;
}

const CONTENT_BY_KIND: Record<PageKind, (spec: WebsiteSpec) => string> = {
  home: homePageContent,
  about: aboutPageContent,
  services: servicesPageContent,
  projects: projectsPageContent,
  contact: contactPageContent,
};

export function pageFileContent(kind: PageKind, spec: WebsiteSpec): string {
  return CONTENT_BY_KIND[kind](spec);
}

export function siteConfigContent(spec: WebsiteSpec): string {
  const nav = spec.pages.map((kind) => {
    const def = pageDef(kind, spec.siteName);
    return { href: def.slug ? `/${def.slug}` : "/", label: def.navLabel };
  });
  return `// Generated by @hermes/website-factory. Do not edit by hand — regenerate
// via \`hermes-website generate\` instead.
export interface NavLink {
  href: string;
  label: string;
}

export interface SiteConfig {
  name: string;
  description: string;
  nav: NavLink[];
}

export const siteConfig: SiteConfig = ${JSON.stringify(
    { name: spec.siteName, description: spec.siteDescription, nav },
    null,
    2,
  )};
`;
}

export function writePages(spec: WebsiteSpec): void {
  const appDir = path.join(projectDir(spec.projectName), "app");
  const validKinds = spec.pages.filter((kind) => ALL_PAGE_KINDS.includes(kind));

  for (const kind of validKinds) {
    const def = pageDef(kind, spec.siteName);
    const targetDir = def.slug ? path.join(appDir, def.slug) : appDir;
    fs.mkdirSync(targetDir, { recursive: true });
    fs.writeFileSync(path.join(targetDir, "page.tsx"), pageFileContent(kind, spec), "utf8");
  }

  const libDir = path.join(projectDir(spec.projectName), "lib");
  fs.mkdirSync(libDir, { recursive: true });
  fs.writeFileSync(path.join(libDir, "site-config.ts"), siteConfigContent(spec), "utf8");
}
